apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: arc-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: ssdaggupati/aks-github-actions-demo
