authSecret:
  create: false
  name: controller-manager

githubWebhookServer:
  enabled: true

metrics:
  serviceMonitor:
    enabled: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5

syncPeriod: 1m
