apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: arc-systems
type: Opaque
stringData:
  github_app_id: "1481766"
  github_app_installation_id: "73567236"
  github_app_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAsRupPrcg2swEPVuHXmW9/CQyA04RJYM1N9i4pbvWCZsH0dd/
H9qJ2SvbtioBt4lLwuRZEL2YlgW8fnFrZOIn7xuKi08ByrW5Rdds4SbHRuayw2cM
QEcoOUpFDkuDCCbc14LsbI+SKUk2fkLYa0r2wXjcmhs/QjdDkCtAPgEBXEmPcMHu
xOtKzY9yUF1frOT16ldtIQqALBb5ddY9ZKxori4YsZeI9xeL/UYSorIugqQlWECS
y8rhBQvzOHfY+drzet3YTt8ShtSyb6GU+BFuIcqIXHQGd8Xg3jLGCyDhx24q7AMQ
XYDbphnUO+Dq4xl7wUTMeZHhM3XWFveR1JXBSQIDAQABAoIBAQCa5DosIzSUpgC/
OKE3KXvyXCVxRoEwcYPFh8BVEeWrGO7J0tHXJeWRDQ5mTm6Z+XVMyTArt+UOr42e
d8sYu8F5GHkeRMaoZi3WqwUKFEQL+g81XZYVUSYYlJ+4VMoQAwz5XgMvHpERknoa
CpQDodgUdINaM6IrYvGv0GOq1m4+KpKK7GEqPqBOOCRMHW+ZSHrAlyIuIaoLkjcR
gWTa5grTfKJm14zIDkRnhV5D3bJDblbqrtLgmRBzdRsmTQkFmN58XmxzUN9FbaqV
6IYT9Js9c6xrlPjI3NezXAZS0pl0V1EBqzaMdwNI0OX+i5/bFxuIgDaqwHJ1q7yi
VOQBvhXRAoGBAN3FwCMdSBvmZRGPPmd/HnwRUvK/ylrepWgo45YVrG99e+0aSd4Y
AS9zdvQLAaONqfTrSoxEEqM/Z3RaaBUtn9QSztqcDYqKe5i3wCLHDFndDOOA2gDp
SUEXFFRuw5nxjilZhNR7Gm4p6wuygTGauZh9D41ilH05qNr9QBuhM+VnAoGBAMxx
NztgUV0wjngamnWoERn+GT5hcqJEy54clTjulS5xCIsWH9xu4EeJtjlwffkPKnzs
Njp8luqxhMWjA5nojsnFFQIV80Ssu8qcMUnm3VA3mKvPm4DAXG1lKV7EeBiVwECi
ZIq1w6KQukkMW/YRcRAhHt0+OiowKB9JlyHF0cXPAoGAKexpHvo5GHUcZA5lKKGC
PMf1m0ggU79FG4SnSUb9mvHozHCsyBxXlQXJ1eaCv81W9KLKK+vubgfdYcR5ao9+
aFPJ4M+hS7BUHxGVc72XGyHLfvJrw8JWA8T+JdvuhBqC2lQ+5QAEhhDMiyCKhbsP
HMF/gCXDlkyhHAzF4rM9oT8CgYAhtyocqK3CaJeWRwziCm2Hk9gl6Xw2NpI96QjS
8sW3evyls2hdugtSwOtEXcDoqg+funTXAGUDH3N+BHw7jZa+v7nPNj+AO9xcdZXL
Uj99Uy3iZ8KFYTPc9qnz7wK/SzMBdcaO+Zrh3GxcT6V61zWGK3AjnHeLLZXwUvqR
n0YREQKBgQCpsf18h8F15YaLJsa3OQyPfizIry699XME+zpRCF6uuV6upyGzpOGJ
BUXOYY/82b5GeuajVf/lvdednI9UPk7uXGJEiJQu32cOy5p1MmOZ3u2VeOHVp852
nmK9g6IHwzEsnLc1V6jTs+uzNBWlDR3XBhLs0/sbwV9KHrnlV6bBxg==
-----END RSA PRIVATE KEY-----