apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gha-cert-manager-clusterrole
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["clusterissuers"]
  verbs: ["get", "create", "update", "patch", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gha-cert-manager-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: arc-runner-set-gha-rs-no-permission
  namespace: arc-runners
roleRef:
  kind: ClusterRole
  name: gha-cert-manager-clusterrole
  apiGroup: rbac.authorization.k8s.io
