apiVersion: actions.github.com/v1alpha1
kind: RunnerScaleSet
metadata:
  name: arc-runner-set
  namespace: arc-systems
spec:
  githubConfigUrl: https://github.com/ssdaggupati/aks-github-actions-demo
  githubConfigSecret:
    name: github-app-secret
    key: github_app
  replicas: 1
  template:
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
