name: Build and Deploy to AKS using Kubeconfig

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: ghademoregistry8419.azurecr.io
  AKS_CLUSTER_NAME: aks-gha-demo
  AKS_RESOURCE_GROUP: aks-gha-demo-rg

jobs:
  build-and-deploy:
    runs-on: arc-runner-set

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to ACR
        run: az acr login --name ghademoregistry8419

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/flask-app:latest ./app
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/flask-app:latest
      - name: Set AKS context using kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
      - name: Deploy to AKS
        run: kubectl apply -f ./manifests
