name: Build and Deploy to AKS using Kubeconfig

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AZURE_CONTAINER_REGISTRY: ghademoregistry8419.azurecr.io
  AKS_CLUSTER_NAME: aks-gha-demo
  AKS_RESOURCE_GROUP: aks-gha-demo-rg

jobs:
  build-and-deploy:
    runs-on: arc-runner-set

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # - name: Login to Azure
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     audience: api://AzureADTokenExchange
      #     allow-no-subscriptions: true
      
      # - name: Debug Azure Subscriptions
      #   run: az account show

      - name: Login to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ env.AZURE_CONTAINER_REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/flask-app:latest ./app
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/flask-app:latest
      
      - name: Set AKS context using kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to AKS
        run: kubectl apply -f ./manifests
